# Generated by Django 5.0.1 on 2024-03-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('des', models.TextField(blank=True, max_length=250)),
                ('cat_img', models.ImageField(blank=True, upload_to='photos/catagories')),
            ],
        ),
    ]
